[package]
name = "minesweeper-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.1"
colored = { version = "2.1.0", optional = true }
rand = "0.8.5"

[features]
default = []
debug = ["colored"]
